# Generated by Django 5.0.4 on 2024-06-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedcapSC2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(max_length=200)),
                ('laboratorio', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('mes_coleta', models.CharField(blank=True, max_length=7, null=True)),
                ('lote', models.IntegerField()),
                ('melhor_repeticao', models.CharField(blank=True, max_length=200, null=True)),
                ('cobertura', models.FloatField()),
                ('profundidade_media', models.FloatField()),
                ('linhagem', models.CharField(blank=True, max_length=50, null=True)),
                ('variante', models.CharField(blank=True, max_length=50, null=True)),
                ('qualidade', models.CharField(blank=True, max_length=8, null=True)),
                ('resultado', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
