# Generated by Django 5.0.4 on 2024-06-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_laboratorio_repeticao_resultado_variante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redcapsc2',
            name='variante',
        ),
        migrations.DeleteModel(
            name='Variante',
        ),
    ]
