# Generated by Django 5.0.4 on 2024-06-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_redcapsc2_variante_delete_variante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='redcapsc2',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SC2_labs', to='app.laboratorio'),
        ),
        migrations.AlterField(
            model_name='redcapsc2',
            name='melhor_repeticao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SC2_repet', to='app.repeticao'),
        ),
        migrations.AlterField(
            model_name='redcapsc2',
            name='resultado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SC2_res', to='app.resultado'),
        ),
        migrations.AddField(
            model_name='redcapsc2',
            name='variante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SC2_var', to='app.variante'),
        ),
    ]
