# Generated by Django 5.0.4 on 2024-06-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_variante_alter_redcapsc2_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redcapsc2',
            name='laboratorio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='SC2_labs', to='app.laboratorio'),
        ),
        migrations.AlterField(
            model_name='redcapsc2',
            name='melhor_repeticao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='SC2_repet', to='app.repeticao'),
        ),
        migrations.AlterField(
            model_name='redcapsc2',
            name='resultado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='SC2_res', to='app.resultado'),
        ),
        migrations.AlterField(
            model_name='redcapsc2',
            name='variante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='SC2_var', to='app.variante'),
        ),
    ]
