# Generated by Django 5.0.4 on 2024-06-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_qualidade_alter_sc2_qualidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc2',
            name='record_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
