# Generated by Django 5.0.4 on 2024-07-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sc2_id2_alter_sc2_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc2',
            name='id2',
        ),
        migrations.AlterField(
            model_name='sc2',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
