# Generated by Django 5.0.4 on 2024-07-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_sc2_id2_alter_sc2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc2',
            name='codigo_gisaid',
            field=models.CharField(default='Não depositado', max_length=200),
        ),
    ]
